// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crcor_rcpp
arma::mat crcor_rcpp(arma::mat x1, arma::mat x2, arma::umat idx1, arma::umat idx2, arma::mat A1, arma::mat A2);
RcppExport SEXP _mfutils_crcor_rcpp(SEXP x1SEXP, SEXP x2SEXP, SEXP idx1SEXP, SEXP idx2SEXP, SEXP A1SEXP, SEXP A2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type idx2(idx2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A2(A2SEXP);
    rcpp_result_gen = Rcpp::wrap(crcor_rcpp(x1, x2, idx1, idx2, A1, A2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mfutils_crcor_rcpp", (DL_FUNC) &_mfutils_crcor_rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mfutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
